### PR TITLE
Add: Swift 4 Module Template

### PR DESCRIPTION
**Pull request by fulldecent**
Please consider to add Swift 3 Module Template. It is a starting point for people that will create their own modules.

### CODE REVIEW

**Comment by vasiliyb** [comment]
Lgtme

**Comment by fulldecent** [comment]
@wolg ... and this one too. Thank you!

**Comment by fulldecent** [comment]
This one is updated too. Please review and approve @vasiliyb @Wolg, thank you!

**Comment by fulldecent** [comment]
Updated URL and title. Now good to merge again.

**Comment by fulldecent** [comment]
Ping. Is this PR in scope for this project?

**Comment by fulldecent** [comment]
Ping. Is this PR in scope for this project?

**Comment by fulldecent** [comment]
- To be clear, are you still accepting contributions to this project?? If so is this PR in scope to be merged?
-

**Pull request merged**
